### ISSUE TITLE
lessc package not available

### ISSUE THREAD

**Issue by fredrikaverpil** [mgyongyosi/OneDarkJekyll#1]
I found your [blog post](http://mgyongyosi.com/2016/atom-one-dark-syntax-with-jekyll/) via google 👍  and attempted to create a rouge/pygments syntax.css for [my Jekyll blog](https://fredrikaverpil.github.io).

However, I quickly noticed that the following did not work on my macOS Sierra (with brew-installed npm):

```bash
$ npm install -g lessc
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "install" "-g" "lessc"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fredrik/code/source/pygments-atom-css/OneDarkJekyll/npm-debug.log
```

I also tried with omitting the `-g` option:

```bash
npm install lessc
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "install" "lessc"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/lessc
npm ERR! 404 
npm ERR! 404  'lessc' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fredrik/code/source/pygments-atom-css/OneDarkJekyll/npm-debug.log
```

When quickly [searching npmjs.org for `lessc`](https://www.npmjs.com/search?q=lessc) I come up short. Perhaps this package is renamed or no longer available?

Either way, I found your pre-cooked `syntax-one-dark.css` in this repo half-way through reading your blog post... and that's what I was looking for in the first place. So for me, problem solved 🥂 as it works really great!

But I figured I'd let you know the instructions in your README doesn't work (at least not for me).

Thanks so much for putting this onto Github! 😄

**Comment by mgyongyosi** [comment]
Hey @fredrikaverpil,

Thank you for your message! 👍  Right now __lessc__ (less compiler) is in the __less__ npm package and __lessc__ is not on npm anymore. The README has been updated.

If you have any improvement for the syntax highlighter please feel free to create a PR (I have only tested it with C#, XML, Ruby and Javascript). :)
